"use client";

/**
 * AI Insights — Gemini-generated operational brief.
 *
 * Calls /api/ai/insights every 90s; the API itself caches the underlying
 * Gemini response for 60s, so we never spam the model.
 */
import { useCallback, useEffect, useState } from "react";
import { Sparkles, RefreshCw } from "lucide-react";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { api, ApiCallError } from "@/lib/api";

type Insight = {
  summary: string;
  bullets: string[];
  model: string;
  latencyMs: number;
  generatedAt: string;
};

export function AIInsightsCard() {
  const [insight, setInsight] = useState<Insight | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback(async (force: boolean) => {
    setRefreshing(true);
    setError(null);
    try {
      const data = await api.get<Insight>(`/api/ai/insights${force ? "?refresh=true" : ""}`);
      setInsight(data);
    } catch (err) {
      setError(err instanceof ApiCallError ? err.message : "Failed to load insights");
    } finally {
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    void load(false);
    const id = window.setInterval(() => void load(false), 90_000);
    return () => window.clearInterval(id);
  }, [load]);

  const fresh = insight ? formatAge(insight.generatedAt) : "";
  const isHeuristic = insight?.model === "heuristic-fallback";

  return (
    <Card className="border-violet-200 bg-gradient-to-br from-violet-50/50 to-white">
      <CardHeader className="flex flex-row items-start justify-between space-y-0 pb-3">
        <div className="flex items-center gap-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-md bg-violet-100">
            <Sparkles className="h-4 w-4 text-violet-600" />
          </div>
          <div>
            <CardTitle className="text-base">AI situation brief</CardTitle>
            <CardDescription className="text-xs">
              {isHeuristic
                ? "Heuristic fallback — set GEMINI_API_KEY on Render to enable live brief"
                : `Generated by ${insight?.model ?? "Gemini 2.5 Flash"} · ${
                    insight ? `${insight.latencyMs} ms` : "—"
                  }${fresh ? ` · ${fresh}` : ""}`}
            </CardDescription>
          </div>
        </div>
        <button
          type="button"
          onClick={() => void load(true)}
          disabled={refreshing}
          className="inline-flex items-center gap-1 rounded-md border bg-background px-2 py-1 text-xs text-muted-foreground transition hover:bg-accent disabled:opacity-50"
        >
          <RefreshCw className={`h-3 w-3 ${refreshing ? "animate-spin" : ""}`} />
          Refresh
        </button>
      </CardHeader>
      <CardContent className="space-y-3">
        {error && (
          <div className="rounded-md border border-destructive/50 bg-destructive/5 p-3 text-xs text-destructive">
            {error}
          </div>
        )}

        {!insight && !error && (
          <div className="space-y-2">
            <div className="h-4 w-3/4 animate-pulse rounded bg-muted" />
            <div className="h-3 w-2/3 animate-pulse rounded bg-muted" />
            <div className="h-3 w-1/2 animate-pulse rounded bg-muted" />
          </div>
        )}

        {insight && (
          <>
            <p className="text-sm font-medium leading-snug">{insight.summary}</p>
            <ul className="space-y-1.5">
              {insight.bullets.map((b, i) => (
                <li key={i} className="flex gap-2 text-xs text-muted-foreground">
                  <span className="mt-1 inline-block h-1.5 w-1.5 shrink-0 rounded-full bg-violet-500" />
                  <span>{b}</span>
                </li>
              ))}
            </ul>
          </>
        )}
      </CardContent>
    </Card>
  );
}

function formatAge(iso: string): string {
  const sec = Math.max(0, Math.round((Date.now() - new Date(iso).getTime()) / 1000));
  if (sec < 60) return `${sec}s ago`;
  if (sec < 3600) return `${Math.round(sec / 60)}m ago`;
  return `${Math.round(sec / 3600)}h ago`;
}
